### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by devark28** [KevinRebakure/ToDo#6]
issue introduced in commit [#fd5f98f](https://github.com/KevinRebakure/ToDo/commit/fd5f98fabd4ea69b9241b53c35787a3522ee5cd1)

the broken link is labeled `Drag and drop Version 2.0`

**Comment by KevinRebakure** [comment]
Can you provide the specifics? Because it's working on my end.

**Comment by devark28** [comment]
netlify might have played a trick on me by then, now it works opens!
